class Bike{
    public static void main(String[] args) {

        System.out.println("break");
        System.out.println("class");
        System.out.println("do");
        System.out.println("byte");
        System.out.println("abstract");
        System.out.println("case");
        System.out.println("do");
        System.out.println("catch");
        System.out.println("char");
        System.out.println("assert");
        System.out.println("continue");
        System.out.println("synchronized");
        System.out.println("default");
        System.out.println("boolean");
        System.out.println("long");
        System.out.println("import");
		System.out.println("valatile");
        System.out.println("while");
        System.out.println("goto");
        System.out.println("const");
        System.out.println("final");
        System.out.println("interface");
        System.out.println("void");
        System.out.println("return");
        System.out.println("protected");
        System.out.println("native");
        System.out.println("new");
        System.out.println("package");
        System.out.println("privete");
        System.out.println("if");
		System.out.println("double");
        System.out.println("else");
        System.out.println("enum");
        System.out.println("extends");
        System.out.println("final");
        System.out.println("finally");
        System.out.println("float");
        System.out.println("implement");
        System.out.println("this");
        System.out.println("public");
        System.out.println("short");
        System.out.println("static");
        System.out.println("stictic");
        System.out.println("super");
        System.out.println("transient");
        System.out.println("for");
        System.out.println("while");
        System.out.println("do");
        System.out.println("switch");
        System.out.println("throws");
        
    }
}